Repository Crescom-SohoCaddie/soho-caddie, pull requests merged in 2021-11, with the labels that each got.

#40 商品項目追加用プラスボタン追加
  mock/mock01_quotaion.html
  mock/mock_invoice.html
Labels: request review

#42 商品項目追加ボタン位置修正
  mock/mock01_quotaion.html
  mock/mock_invoice.html
Labels: request review

#41 Dockerfile作成
  Dockerfile
Labels: request review

#45 デザイン指摘箇所修正
  mock/mock01_quotaion.html
  mock/mock_invoice.html
Labels: request review

#47 main.py作成
  Dockerfile
  app/main.py
Labels: request review

#50 更新・印刷ボタンを右下にも配置
  mock/mock01_quotaion.html
  mock/mock_invoice.html
Labels: request review

#52 各種情報設定画面　途中まで作成
  mock/mock_settings.html
Labels: wip

#54 各種情報設定ページモック完成
  mock/mock_settings.html
Labels: request review

#55 更新・印刷・取消ボタンを追従フッターに配置
  mock/mock01_quotaion.html
  mock/mock_customer.html
  mock/mock_invoice.html
  mock/mock_item.html
  mock/mock_settings.html
Labels: request review

#58 フッターの背景透過度上げる
  mock/mock01_quotaion.html
  mock/mock_customer.html
  mock/mock_invoice.html
  mock/mock_item.html
  mock/mock_settings.html
Labels: request review

#61 入力欄のラベル「タイトル」を「件名」に変更
  mock/mock01_quotaion.html
  mock/mock_invoice.html
Labels: request review

#66 顧客選択モーダル実装
  mock/mock01_quotaion.html
  mock/mock_invoice.html
Labels: request review

#69 得意先情報削除。メモ追加。
  mock/mock01_quotaion.html
  mock/mock_invoice.html
Labels: request review

#71 各機能の一覧表示ページ作成
  mock/images/trash.png
  mock/mock01_quotaion.html
  mock/mock_customer.html
  mock/mock_invoice.html
  mock/mock_item.html
Labels: request review

#73 メモと備考欄は別物なので切り分ける
  mock/mock01_quotaion.html
  mock/mock_customer.html
  mock/mock_invoice.html
  mock/mock_item.html
Labels: request review

#74 テーブルの水色ストライプを全テーブルに適用
  mock/mock01_quotaion.html
  mock/mock_customer.html
  mock/mock_invoice.html
  mock/mock_item.html
  mock/mock_settings.html
Labels: request review

#77 画面切替方法の追加
  mock/mock01_quotaion.html
Labels: in progress

#78 サイドバーの閉じるボタンを右上に
  mock/mock01_quotaion.html
  mock/mock_customer.html
  mock/mock_invoice.html
  mock/mock_item.html
  mock/mock_settings.html
Labels: request review

#79 DB設計表(Customer)作成
  models.md
Labels: request review

#80 DB設計表一旦完成？
  models.md
Labels: request review

#81 設計表修正
  models.md
Labels: request review

#82 ER図を作成
  models.md
  soho_er.dio
Labels: request review

#83 ER図を画像にエクスポート
  soho_er.dio
  soho_er.png
Labels: request review

#84 model sample
  monolith/monolith.py
Labels: request review

#85 モノリスモジュール分け。うまく動かない
  monolith-module/app.py
  monolith-module/models.py
Labels: request review

#87 モデルモジュール化。とりあえず動く
  monolith-module/.gitignore
  monolith-module/models.py
Labels: request review

#88 seeder途中まで
  monolith-module/models.py
  monolith-module/seeder.py
Labels: wip

#90 seeder完成
  monolith-module/seeder.py
Labels: request review

#91 得意先(Customer)テスト一旦完成
  monolith-module/customer_test.py
Labels: request review

#93 Memosまでユニットテスト作成完了
  monolith-module/invoice_item_test.py
  monolith-module/invoice_test.py
  monolith-module/item_test.py
  monolith-module/memo_test.py
  monolith-module/quotaion_item_test.py
  monolith-module/quotaion_test.py
Labels: request review

#98 リレーションうまくいかない
  monolith-module/customer_test.py
  monolith-module/models.py
Labels: wip

#97 ユニットテスト完成
  monolith-module/customer_test.py
  monolith-module/models.py
  monolith-module/seeder.py
  monolith-module/setting_test.py
  monolith-module/unit_test.py
Labels: request review

#99 リレーションのテスト作成
  monolith-module/customer_test.py
  monolith-module/invoice_item_test.py
  monolith-module/models.py
  monolith-module/quotaion_item_test.py
Labels: request review

#101 Customer(得意先)の基本CRUD作成
  monolith-module/api.py
Labels: request review

#102 商品(Item)基本CRUD作成
  monolith-module/api.py
  monolith-module/models.py
Labels: request review

#103 MarshmallowでDictionary取得。Customerのみ
  monolith-module/api.py
  monolith-module/app.py
  monolith-module/customer_test.py
  monolith-module/models.py
Labels: request review

#104 テスト書き直し
  monolith-module/customer_test.py
  monolith-module/invoice_item_test.py
  monolith-module/invoice_test.py
  monolith-module/item_test.py
  monolith-module/memo_test.py
  monolith-module/quotaion_item_test.py
  monolith-module/quotaion_test.py
  monolith-module/seeder.py
  monolith-module/setting_test.py
  monolith-module/unit_test.py
Labels: request review

#106 全基本CRUD作成
  monolith-module/api.py
  monolith-module/models.py
Labels: request review

#107 一覧取得APIを複数形に
  app/api.py
Labels: request review

#111 値段周りのカラム変更
  app/api.py
  app/customer_test.py
  app/invoice_item_test.py
  app/item_test.py
  app/models.py
  app/quotaion_item_test.py
  app/seeder.py
  models.md
  soho_er.dio
  soho_er.png
Labels: request review

#114 Userテーブル・その他必要なもの追加
  app/api.py
  app/models.py
  app/seeder.py
  app/user_test.py
  models.md
  soho_er.dio
  soho_er.png
Labels: request review
